### ISSUE TITLE
make ERROR

### ISSUE THREAD

**Issue by hgz07** [wardenlym/apns2-test#1]
Makefile.am: installing './INSTALL'
examples/Makefile.am: installing './depcomp'
lib/Makefile.am:35: error: Libtool library used but 'LIBTOOL' is undefined
lib/Makefile.am:35:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
lib/Makefile.am:35:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
lib/Makefile.am:35:   If 'LT_INIT' is in 'configure.ac', make sure
lib/Makefile.am:35:   its definition is in aclocal's search path.
src/Makefile.am:147: error: library used but 'RANLIB' is undefined
src/Makefile.am:147:   The usual way to define 'RANLIB' is to add 'AC_PROG_RANLIB'
src/Makefile.am:147:   to 'configure.ac' and run 'autoconf' again.
src/Makefile.am:221: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:221:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:221:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:221:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:221:   its definition is in aclocal's search path.
parallel-tests: installing './test-driver'
third-party/Makefile.am:28: error: Libtool library used but 'LIBTOOL' is undefined
third-party/Makefile.am:28:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
third-party/Makefile.am:28:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
third-party/Makefile.am:28:   If 'LT_INIT' is in 'configure.ac', make sure
third-party/Makefile.am:28:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
make: **\* [deps/nghttp2/lib/.libs/libnghttp2.a] Error 1

**Comment by wardenlym** [comment]
thx!
I'm not sure whether _libtool_ configured correctly on your environment.
The following package is required to build the libnghttp2 library:
pkg-config >= 0.20
OpenSSL >= 1.0.1
aka,
If you are using Ubuntu 14.04 LTS (trusty) or Debian 7.0 (wheezy) and above run the following to install the needed packages:

```
sudo apt-get install g++ make binutils autoconf automake autotools-dev libtool pkg-config libssl-dev
```

**Comment by wardenlym** [comment]
.
